### ISSUE TITLE
Error: Could not find or load main class com.instaclustr.sstabletools.SummaryCollecto

### ISSUE THREAD

**Issue by sb355v** [instaclustr/cassandra-sstable-tools#1]
Not able to find  ic-sstable-tools.jar to be copied in cassandra home and also seeing  Error: Could not find or load main class com.instaclustr.sstabletools.SummaryCollecto error.

**Comment by mohammedguller** [comment]
Copy ic-sstable-tools.jar to the lib directory of your C* setup.
